package com.component.dbdao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.component.model.db.ATypeListEntity;
import com.component.model.db.BudgetBo;
import com.component.model.db.ListItemBO;
import com.component.model.db.CategoryEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aTypeListEntityDaoConfig;
    private final DaoConfig budgetBoDaoConfig;
    private final DaoConfig listItemBODaoConfig;
    private final DaoConfig categoryEntityDaoConfig;

    private final ATypeListEntityDao aTypeListEntityDao;
    private final BudgetBoDao budgetBoDao;
    private final ListItemBODao listItemBODao;
    private final CategoryEntityDao categoryEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aTypeListEntityDaoConfig = daoConfigMap.get(ATypeListEntityDao.class).clone();
        aTypeListEntityDaoConfig.initIdentityScope(type);

        budgetBoDaoConfig = daoConfigMap.get(BudgetBoDao.class).clone();
        budgetBoDaoConfig.initIdentityScope(type);

        listItemBODaoConfig = daoConfigMap.get(ListItemBODao.class).clone();
        listItemBODaoConfig.initIdentityScope(type);

        categoryEntityDaoConfig = daoConfigMap.get(CategoryEntityDao.class).clone();
        categoryEntityDaoConfig.initIdentityScope(type);

        aTypeListEntityDao = new ATypeListEntityDao(aTypeListEntityDaoConfig, this);
        budgetBoDao = new BudgetBoDao(budgetBoDaoConfig, this);
        listItemBODao = new ListItemBODao(listItemBODaoConfig, this);
        categoryEntityDao = new CategoryEntityDao(categoryEntityDaoConfig, this);

        registerDao(ATypeListEntity.class, aTypeListEntityDao);
        registerDao(BudgetBo.class, budgetBoDao);
        registerDao(ListItemBO.class, listItemBODao);
        registerDao(CategoryEntity.class, categoryEntityDao);
    }
    
    public void clear() {
        aTypeListEntityDaoConfig.clearIdentityScope();
        budgetBoDaoConfig.clearIdentityScope();
        listItemBODaoConfig.clearIdentityScope();
        categoryEntityDaoConfig.clearIdentityScope();
    }

    public ATypeListEntityDao getATypeListEntityDao() {
        return aTypeListEntityDao;
    }

    public BudgetBoDao getBudgetBoDao() {
        return budgetBoDao;
    }

    public ListItemBODao getListItemBODao() {
        return listItemBODao;
    }

    public CategoryEntityDao getCategoryEntityDao() {
        return categoryEntityDao;
    }

}
